# The base docker-compose
version: "3.3"
services:
  cf-phx:
    depends_on:
      - db
    command: ["bin/start_cf_phx.sh"]
    build:
      context: .
      dockerfile: Dockerfile.cf-http
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/cloudfire

      # !! WARNING !!
      # Change this for production systems!
      # !!!!!!!!!!!!!
      SECRET_KEY_BASE: vw5YEoG6Pb7mCQEC41DjJXIB6v1/tOxO+3YLN+5k+PILkcFMN54g22KXZr6o65Bn
      ERL_COOKIE: bSHTSulle4fn4ZgH3CgT6gEEtLiH9leOh1Ykeo4JEEyG31aeDZnDwEWCIhEKM0kF
    ports:
      - 4000:4000
    networks:
      - cloudfire

  system-engine:
    depends_on:
       - db
    command: ["system_engine/bin/system_engine", "start"]
    build:
      context: .
      dockerfile: Dockerfile.cf-wg
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/cloudfire

      # !! WARNING !!
      # Change these for production systems!
      # !!!!!!!!!!!!!
      SECRET_KEY_BASE: vw5YEoG6Pb7mCQEC41DjJXIB6v1/tOxO+3YLN+5k+PILkcFMN54g22KXZr6o65Bn
      ERL_COOKIE: bSHTSulle4fn4ZgH3CgT6gEEtLiH9leOh1Ykeo4JEEyG31aeDZnDwEWCIhEKM0kF
    networks:
      - cloudfire

  db:
    networks:
      - cloudfire
    image: postgres:12
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      # !! WARNING !!
      # Change this for production systems!
      # !!!!!!!!!!!!!
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432


volumes:
  pg-data:

networks:
  cloudfire:
